In [1]:
import pandas as pd   # it's a library used process the tubular data

In [2]:
dataset= pd.read_csv("CKD.csv")  # function of pandas used to load the data
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset) #to create dummies value for categorical text
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,cad_no,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes,classification_no,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,True,False,False,True,False,True,True,False,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,True,True,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,True,True,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,True,True,False,False,True,False,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,True,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,True,True,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,False,True,False,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,True,False,True,False,True,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,False,True,False,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,True,True,False,True,False,True,False

In [4]:
dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false
dataset

C:\Users\jayas\AppData\Local\Temp\ipykernel_17036\2063786219.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,cad_no,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes,classification_no,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,1,0,1,1,0,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,1,1,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,1,1,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,1,1,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,1,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,1,1,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,1,0,1,0,1,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,1,1,0,1,0,1,0

In [5]:
dataset = dataset.drop(columns=['cad_no', 'classification_no', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_a', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_abnormal',
       'rbc_normal', 'pc_abnormal', 'pc_normal', 'pcc_notpresent',
       'pcc_present', 'ba_notpresent', 'ba_present', 'htn_no', 'htn_yes'])# drop columns from the dataset
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,dm_no,dm_yes,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,1,0,0,0,1,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,1,0,0,0,1,1,0,1,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,1,0,0,0,1,1,0,1,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,1,0,0,0,1,1,0,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,1,0,0,0,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,1,0,0,0,1,1,0,1,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,0,1,0,0,1,1,0,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,0,1,0,1,0,1,0,1,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,0,1,0,0,1,1,0,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,1,0,0,0,1,1,0,1,0,0

In [6]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 
       'dm_no', 'dm_yes', 'cad_yes', 'appet_poor', 'appet_yes', 'pe_poor',
       'pe_yes', 'ane_no', 'ane_yes']]  # split input and output to get input from dataset 
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,dm_no,dm_yes,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,1,0,0,0,1,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,1,0,0,0,1,1,0,1,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,1,0,0,0,1,1,0,1,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,1,0,0,0,1,1,0,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,1,0,0,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,1,0,0,0,1,1,0,1,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,0,1,0,0,1,1,0,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,0,1,0,1,0,1,0,1,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,0,1,0,0,1,1,0,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,1,0,0,0,1,1,0,1,0

In [7]:
dependent=dataset[['classification_yes']] # get output from dataset
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split  # sklearn library for machine learning
x_train,x_test,y_train,y_test = train_test_split(independent, dependent,test_size=0.30,random_state=0)

In [9]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import GridSearchCV # built model for grid search and cross validation
param_grid= param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.5, 1.0],
    'algorithm': ['SAMME', 'SAMME.R']}

grid= GridSearchCV( AdaBoostClassifier(),param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
60 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'algorithm' parameter of AdaBoostClassifier must be a str among {'SAMME'}. Got 'SAMME.R' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [0.8925974  0.8925974  0.8925974  0.92837662 0.94987013 0.95344156
 0.95701299 0.94272727 0.94279221 0.94636364 0.94993506 0.94279221
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
  warnings.warn(
C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(

GridSearchCV(estimator=AdaBoostClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['SAMME', 'SAMME.R'],
                         'learning_rate': [0.01, 0.1, 0.5, 1.0],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [10]:
re=grid.cv_results_ # print best parameter after tuning

In [11]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_learning_rate,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.566742,0.017320,0.058897,0.010642,SAMME,0.01,50,"{'algorithm': 'SAMME', 'learning_rate': 0.01, ...",0.875000,0.821429,0.892857,0.946429,0.927273,0.892597,0.043531,10
1,0.835576,0.124459,0.090465,0.017393,SAMME,0.01,100,"{'algorithm': 'SAMME', 'learning_rate': 0.01, ...",0.875000,0.821429,0.892857,0.946429,0.927273,0.892597,0.043531,10
2,1.554397,0.088150,0.193599,0.002633,SAMME,0.01,200,"{'algorithm': 'SAMME', 'learning_rate': 0.01, ...",0.875000,0.821429,0.892857,0.946429,0.927273,0.892597,0.043531,10
3,0.429349,0.012926,0.058683,0.014855,SAMME,0.10,50,"{'algorithm': 'SAMME', 'learning_rate': 0.1, '...",0.928571,0.857143,0.928571,0.982143,0.945455,0.928377,0.040637,9
4,0.815624,0.039182,0.113668,0.023153,SAMME,0.10,100,"{'algorithm': 'SAMME', 'learning_rate': 0.1, '...",0.928571,0.892857,0.982143,0.982143,0.963636,0.949870,0.034574,4
5,1.610168,0.049031,0.181868,0.006897,SAMME,0.10,200,"{'algorithm': 'SAMME', 'learning_rate': 0.1, '...",0.928571,0.910714,0.982143,0.982143,0.963636,0.953442,0.028968,2
6,0.413500,0.016578,0.055646,0.001807,SAMME,0.50,50,"{'algorithm': 'SAMME', 'learning_rate': 0.5, '...",0.928571,0.928571,0.982143,0.982143,0.963636,0.957013,0.024186,1
7,0.789976,0.017681,0.100633,0.005319,SAMME,0.50,100,"{'algorithm': 'SAMME', 'learning_rate': 0.5, '...",0.928571,0.910714,0.946429,0.964286,0.963636,0.942727,0.020692,8
8,1.567482,0.019655,0.179882,0.006176,SAMME,0.50,200,"{'algorithm': 'SAMME', 'learning_rate': 0.5, '...",0.928571,0.910714,0.946429,0.946429,0.981818,0.942792,0.023583,7
9,0.394390,0.014253,0.057754,0.004635,SAMME,1.00,50,"{'algorithm': 'SAMME', 'learning_rate': 1.0, '...",0.928571,0.928571,0.946429,0.946429,0.981818,0.946364,0.019443,5
10,0.779897,0.017283,0.100020,0.010217,SAMME,1.00,100,"{'algorithm': 'SAMME', 'learning_rate': 1.0, '...",0.892857,0.946429,0.946429,0.982143,0.981818,0.949935,0.032669,3
11,1.476683,0.033764,0.157795,0.014628,SAMME,1.00,200,"{'algorithm': 'SAMME', 'learning_rate': 1.0, '...",0.892857,0.928571,0.928571,0.982143,0.981818,0.942792,0.034553,6
12,0.003695,0.000565,0.000000,0.000000,SAMME.R,0.01,50,"{'algorithm': 'SAMME.R', 'learning_rate': 0.01...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.003210,0.001637,0.000000,0.000000,SAMME.R,0.01,100,"{'algorithm': 'SAMME.R', 'learning_rate': 0.01...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,0.002728,0.000129,0.000000,0.000000,SAMME.R,0.01,200,"{'algorithm': 'SAMME.R', 'learning_rate': 0.01...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
15,0.002517,0.000904,0.000000,0.000000,SAMME.R,0.10,50,"{'algorithm': 'SAMME.R', 'learning_rate': 0.1,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
16,0.002683,0.001264,0.000000,0.000000,SAMME.R,0.10,100,"{'algorithm': 'SAMME.R', 'learning_rate': 0.1,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
17,0.002421,0.000972,0.000000,0.000000,SAMME.R,0.10,200,"{'algorithm': 'SAMME.R', 'learning_rate': 0.1,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
18,0.002430,0.000468,0.000000,0.000000,SAMME.R,0.50,50,"{'algorithm': 'SAMME.R', 'learning_rate': 0.5,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
19,0.002294,0.000607,0.000000,0.000000,SAMME.R,0.50,100,"{'algorithm': 'SAMME.R', 'learning_rate': 0.5,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
20,0.003756,0.001517,0.000000,0.000000,SAMME.R,0.50,200,"{'algorithm': 'SAMME.R', 'learning_rate': 0.5,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
21,0.002059,0.001147,0.000000,0.000000,SAMME.R,1.00,50,"{'algorithm': 'SAMME.R', 'learning_rate': 1.0,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
22,0.002802,0.000478,0.000000,0.000000,SAMME.R,1.00,100,"{'algorithm': 'SAMME.R', 'learning_rate': 1.0,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
23,0.003005,0.000532,0.000000,0.000000,SAMME.R,1.00,200,"{'algorithm': 'SAMME.R', 'learning_rate': 1.0,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13

In [12]:
grid_predictions = grid.predict(x_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

In [14]:
print(cm)

[[43  2]
 [ 3 72]]

In [15]:
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [16]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.93      0.96      0.95        45
           1       0.97      0.96      0.97        75

    accuracy                           0.96       120
   macro avg       0.95      0.96      0.96       120
weighted avg       0.96      0.96      0.96       120

In [17]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

np.float64(0.9931851851851852)