In [1]:
import pandas as pd   # it's a library used process the tubular data

In [2]:
dataset= pd.read_csv("CKD.csv")  # function of pandas used to load the data
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset) #to create dummies value for categorical text
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,cad_no,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes,classification_no,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,True,False,False,True,False,True,True,False,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,True,True,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,True,True,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,True,True,False,False,True,False,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,True,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,True,True,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,False,True,False,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,True,False,True,False,True,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,False,True,False,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,True,True,False,True,False,True,False

In [4]:
dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false
dataset

C:\Users\jayas\AppData\Local\Temp\ipykernel_28184\2063786219.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,cad_no,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes,classification_no,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,1,0,1,1,0,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,1,1,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,1,1,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,1,1,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,1,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,1,1,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,1,0,1,0,1,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,1,1,0,1,0,1,0

In [5]:
dataset = dataset.drop(columns=['cad_no', 'classification_no', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_a', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_abnormal',
       'rbc_normal', 'pc_abnormal', 'pc_normal', 'pcc_notpresent',
       'pcc_present', 'ba_notpresent', 'ba_present', 'htn_no', 'htn_yes'])# drop columns from the dataset
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,dm_no,dm_yes,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,1,0,0,0,1,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,1,0,0,0,1,1,0,1,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,1,0,0,0,1,1,0,1,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,1,0,0,0,1,1,0,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,1,0,0,0,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,1,0,0,0,1,1,0,1,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,0,1,0,0,1,1,0,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,0,1,0,1,0,1,0,1,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,0,1,0,0,1,1,0,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,1,0,0,0,1,1,0,1,0,0

In [6]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 
       'dm_no', 'dm_yes', 'cad_yes', 'appet_poor', 'appet_yes', 'pe_poor',
       'pe_yes', 'ane_no', 'ane_yes']]  # split input and output to get input from dataset 
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,dm_no,dm_yes,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,1,0,0,0,1,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,1,0,0,0,1,1,0,1,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,1,0,0,0,1,1,0,1,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,1,0,0,0,1,1,0,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,1,0,0,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,1,0,0,0,1,1,0,1,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,0,1,0,0,1,1,0,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,0,1,0,1,0,1,0,1,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,0,1,0,0,1,1,0,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,1,0,0,0,1,1,0,1,0

In [7]:
dependent=dataset[['classification_yes']] # get output from dataset
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split  # sklearn library for machine learning
x_train,x_test,y_train,y_test = train_test_split(independent, dependent,test_size=0.30,random_state=0)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV # built model for grid search and cross validation
param_grid = {
    'penalty': ['l1', 'l2', 'elasticnet', 'none'],
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'saga'],
    'max_iter': [100, 200, 500],
    'l1_ratio': [0, 0.5, 1]}


grid= GridSearchCV(LogisticRegression(),param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 432 candidates, totalling 2160 fits

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
810 fits failed out of a total of 2160.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
270 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 71, in _check_solver
    raise ValueError(
        f"Only 'saga' solver supports elasticnet penalty, got solver={solver}."
    )
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
162 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'elasticnet', 'l2', 'l1'} or None. Got 'none' instead.

--------------------------------------------------------------------------------
193 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l1', 'elasticnet', 'l2'} or None. Got 'none' instead.

--------------------------------------------------------------------------------
97 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l2', 'l1', 'elasticnet'} or None. Got 'none' instead.

--------------------------------------------------------------------------------
68 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l1', 'l2', 'elasticnet'} or None. Got 'none' instead.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l2', 'elasticnet', 'l1'} or None. Got 'none' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [0.63441558 0.63441558 0.83876623 0.84233766        nan 0.84233766
        nan        nan 0.63441558 0.63441558 0.83876623 0.83519481
        nan 0.83519481        nan        nan 0.63441558 0.63441558
 0.83876623 0.83876623        nan 0.83876623        nan        nan
 0.63441558 0.63441558 0.83876623 0.84233766        nan 0.7812987
        nan        nan 0.63441558 0.63441558 0.83876623 0.83519481
        nan 0.7812987         nan        nan 0.63441558 0.63441558
 0.83876623 0.83876623        nan 0.7812987         nan        nan
 0.63441558 0.63441558 0.83876623 0.84233766        nan 0.63441558
        nan        nan 0.63441558 0.63441558 0.83876623 0.83519481
        nan 0.63441558        nan        nan 0.63441558 0.63441558
 0.83876623 0.83876623        nan 0.63441558        nan        nan
 0.82448052 0.82090909 0.85668831 0.83512987        nan 0.83512987
        nan        nan 0.82448052 0.82448052 0.85668831 0.82798701
        nan 0.82798701        nan        nan 0.82448052 0.82448052
 0.85668831 0.83512987        nan 0.83512987        nan        nan
 0.82448052 0.82090909 0.85668831 0.83512987        nan 0.82441558
        nan        nan 0.82448052 0.82448052 0.85668831 0.82798701
        nan 0.81363636        nan        nan 0.82448052 0.82448052
 0.85668831 0.83512987        nan 0.81720779        nan        nan
 0.82448052 0.82090909 0.85668831 0.83512987        nan 0.82090909
        nan        nan 0.82448052 0.82448052 0.85668831 0.82798701
        nan 0.82448052        nan        nan 0.82448052 0.82448052
 0.85668831 0.83512987        nan 0.82448052        nan        nan
 0.89980519 0.83155844 0.93194805 0.83512987        nan 0.83512987
        nan        nan 0.89980519 0.82441558 0.93194805 0.82798701
        nan 0.83155844        nan        nan 0.89980519 0.82798701
 0.93194805 0.8387013         nan 0.8387013         nan        nan
 0.89980519 0.83155844 0.93194805 0.8387013         nan 0.83155844
        nan        nan 0.89980519 0.82441558 0.93194805 0.82798701
        nan 0.82441558        nan        nan 0.89980519 0.82798701
 0.93194805 0.8387013         nan 0.83512987        nan        nan
 0.89980519 0.83155844 0.93194805 0.8387013         nan 0.83155844
        nan        nan 0.89980519 0.82441558 0.93194805 0.82798701
        nan 0.82441558        nan        nan 0.89980519 0.83155844
 0.93194805 0.8387013         nan 0.83155844        nan        nan
 0.94266234 0.83155844 0.94623377 0.8387013         nan 0.8387013
        nan        nan 0.94266234 0.82798701 0.94623377 0.83155844
        nan 0.83155844        nan        nan 0.94266234 0.83512987
 0.94623377 0.8387013         nan 0.8387013         nan        nan
 0.94266234 0.83512987 0.94623377 0.8387013         nan 0.83512987
        nan        nan 0.94266234 0.82798701 0.94623377 0.83155844
        nan 0.82798701        nan        nan 0.94266234 0.83512987
 0.94623377 0.8387013         nan 0.8387013         nan        nan
 0.94266234 0.83155844 0.94623377 0.8387013         nan 0.83512987
        nan        nan 0.94266234 0.82798701 0.94623377 0.83155844
        nan 0.82798701        nan        nan 0.94266234 0.83512987
 0.94623377 0.8387013         nan 0.83512987        nan        nan
 0.9462987  0.8387013  0.94266234 0.8387013         nan 0.83512987
        nan        nan 0.9462987  0.83155844 0.94266234 0.83155844
        nan 0.83155844        nan        nan 0.9462987  0.8387013
 0.94266234 0.8387013         nan 0.8387013         nan        nan
 0.9462987  0.8387013  0.94266234 0.8387013         nan 0.8387013
        nan        nan 0.9462987  0.83155844 0.94266234 0.83155844
        nan 0.83155844        nan        nan 0.9462987  0.8387013
 0.94266234 0.8387013         nan 0.8387013         nan        nan
 0.9462987  0.8387013  0.94266234 0.8387013         nan 0.8387013
        nan        nan 0.9462987  0.83155844 0.94266234 0.83155844
        nan 0.83155844        nan        nan 0.9462987  0.8387013
 0.94266234 0.8387013         nan 0.8387013         nan        nan
 0.94272727 0.8387013  0.94272727 0.8387013         nan 0.83512987
        nan        nan 0.94272727 0.83155844 0.94272727 0.83155844
        nan 0.83155844        nan        nan 0.94272727 0.8387013
 0.94272727 0.8387013         nan 0.8387013         nan        nan
 0.94272727 0.8387013  0.94272727 0.8387013         nan 0.8387013
        nan        nan 0.94272727 0.83155844 0.94272727 0.83155844
        nan 0.83155844        nan        nan 0.94272727 0.8387013
 0.94272727 0.8387013         nan 0.8387013         nan        nan
 0.94272727 0.83512987 0.94272727 0.83512987        nan 0.83512987
        nan        nan 0.94272727 0.83155844 0.94272727 0.83155844
        nan 0.83155844        nan        nan 0.94272727 0.8387013
 0.94272727 0.8387013         nan 0.8387013         nan        nan]
  warnings.warn(
C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1196: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100],
                         'l1_ratio': [0, 0.5, 1], 'max_iter': [100, 200, 500],
                         'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                         'solver': ['liblinear', 'saga']},
             verbose=3)

In [10]:
re=grid.cv_results_ # print best parameter after tuning

In [11]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_l1_ratio,param_max_iter,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.026562,0.004212,0.015830,0.002032,0.001,0.0,100,l1,liblinear,"{'C': 0.001, 'l1_ratio': 0, 'max_iter': 100, '...",0.625000,0.607143,0.625000,0.678571,0.636364,0.634416,0.023978,250
1,0.029763,0.004394,0.015744,0.002953,0.001,0.0,100,l1,saga,"{'C': 0.001, 'l1_ratio': 0, 'max_iter': 100, '...",0.625000,0.607143,0.625000,0.678571,0.636364,0.634416,0.023978,250
2,0.018699,0.004278,0.015461,0.001145,0.001,0.0,100,l2,liblinear,"{'C': 0.001, 'l1_ratio': 0, 'max_iter': 100, '...",0.839286,0.875000,0.857143,0.767857,0.854545,0.838766,0.037223,86
3,0.039470,0.002464,0.014137,0.002165,0.001,0.0,100,l2,saga,"{'C': 0.001, 'l1_ratio': 0, 'max_iter': 100, '...",0.857143,0.875000,0.839286,0.785714,0.854545,0.842338,0.030498,82
4,0.002081,0.000599,0.000000,0.000000,0.001,0.0,100,elasticnet,liblinear,"{'C': 0.001, 'l1_ratio': 0, 'max_iter': 100, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,0.132804,0.005316,0.013257,0.001766,100.000,1.0,500,l2,saga,"{'C': 100, 'l1_ratio': 1, 'max_iter': 500, 'pe...",0.839286,0.857143,0.857143,0.803571,0.836364,0.838701,0.019596,118
428,0.003496,0.001180,0.000000,0.000000,100.000,1.0,500,elasticnet,liblinear,"{'C': 100, 'l1_ratio': 1, 'max_iter': 500, 'pe...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,271
429,0.167626,0.009107,0.013289,0.001937,100.000,1.0,500,elasticnet,saga,"{'C': 100, 'l1_ratio': 1, 'max_iter': 500, 'pe...",0.839286,0.857143,0.857143,0.803571,0.836364,0.838701,0.019596,118
430,0.002466,0.000597,0.000000,0.000000,100.000,1.0,500,none,liblinear,"{'C': 100, 'l1_ratio': 1, 'max_iter': 500, 'pe...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,271
431,0.003011,0.000584,0.000000,0.000000,100.000,1.0,500,none,saga,"{'C': 100, 'l1_ratio': 1, 'max_iter': 500, 'pe...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,271

In [12]:
grid_predictions = grid.predict(x_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

In [14]:
print(cm)

[[42  3]
 [ 4 71]]

In [15]:
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [16]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.91      0.93      0.92        45
           1       0.96      0.95      0.95        75

    accuracy                           0.94       120
   macro avg       0.94      0.94      0.94       120
weighted avg       0.94      0.94      0.94       120

In [17]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

np.float64(0.989925925925926)