In [1]:
import pandas as pd   # it's a library used process the tubular data

In [2]:
dataset= pd.read_csv("CKD.csv")  # function of pandas used to load the data
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset) #to create dummies value for categorical text
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,cad_no,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes,classification_no,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,True,False,False,True,False,True,True,False,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,True,True,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,True,True,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,True,True,False,False,True,False,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,True,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,True,True,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,False,True,False,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,True,False,True,False,True,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,False,True,False,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,True,True,False,True,False,True,False

In [4]:
dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false
dataset

C:\Users\jayas\AppData\Local\Temp\ipykernel_10176\2063786219.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,cad_no,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes,classification_no,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,1,0,1,1,0,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,1,1,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,1,1,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,1,1,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,1,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,1,1,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,1,0,1,0,1,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,1,1,0,1,0,1,0

In [5]:
dataset = dataset.drop(columns=['cad_no', 'classification_no', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_a', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_abnormal',
       'rbc_normal', 'pc_abnormal', 'pc_normal', 'pcc_notpresent',
       'pcc_present', 'ba_notpresent', 'ba_present', 'htn_no', 'htn_yes'])# drop columns from the dataset
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,dm_no,dm_yes,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,1,0,0,0,1,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,1,0,0,0,1,1,0,1,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,1,0,0,0,1,1,0,1,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,1,0,0,0,1,1,0,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,1,0,0,0,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,1,0,0,0,1,1,0,1,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,0,1,0,0,1,1,0,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,0,1,0,1,0,1,0,1,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,0,1,0,0,1,1,0,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,1,0,0,0,1,1,0,1,0,0

In [6]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 
       'dm_no', 'dm_yes', 'cad_yes', 'appet_poor', 'appet_yes', 'pe_poor',
       'pe_yes', 'ane_no', 'ane_yes']]  # split input and output to get input from dataset 
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,dm_no,dm_yes,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,1,0,0,0,1,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,1,0,0,0,1,1,0,1,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,1,0,0,0,1,1,0,1,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,1,0,0,0,1,1,0,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,1,0,0,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,1,0,0,0,1,1,0,1,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,0,1,0,0,1,1,0,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,0,1,0,1,0,1,0,1,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,0,1,0,0,1,1,0,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,1,0,0,0,1,1,0,1,0

In [7]:
dependent=dataset[['classification_yes']] # get output from dataset
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split  # sklearn library for machine learning
x_train,x_test,y_train,y_test = train_test_split(independent, dependent,test_size=0.30,random_state=0)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV # built model for grid search and cross validation
param_grid= param_grid = param_grid = {
    'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'p': [1, 2]}


grid= GridSearchCV( KNeighborsClassifier(),param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 64 candidates, totalling 320 fits

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 5, 7, 9], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [10]:
re=grid.cv_results_ # print best parameter after tuning

In [11]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.020966,0.005146,3.975203,0.082375,auto,3,1,uniform,"{'algorithm': 'auto', 'n_neighbors': 3, 'p': 1...",0.857143,0.857143,0.910714,0.839286,0.890909,0.871039,0.025936,9
1,0.016248,0.002690,2.330628,1.890513,auto,3,1,distance,"{'algorithm': 'auto', 'n_neighbors': 3, 'p': 1...",0.857143,0.857143,0.910714,0.839286,0.890909,0.871039,0.025936,9
2,0.011649,0.000945,0.055320,0.004898,auto,3,2,uniform,"{'algorithm': 'auto', 'n_neighbors': 3, 'p': 2...",0.857143,0.839286,0.892857,0.803571,0.890909,0.856753,0.033477,29
3,0.011414,0.001215,0.021181,0.008415,auto,3,2,distance,"{'algorithm': 'auto', 'n_neighbors': 3, 'p': 2...",0.857143,0.839286,0.892857,0.785714,0.890909,0.853182,0.039391,33
4,0.013556,0.001525,0.035182,0.004156,auto,5,1,uniform,"{'algorithm': 'auto', 'n_neighbors': 5, 'p': 1...",0.910714,0.857143,0.928571,0.803571,0.890909,0.878182,0.044201,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,0.009742,0.002446,0.014294,0.002133,brute,7,2,distance,"{'algorithm': 'brute', 'n_neighbors': 7, 'p': ...",0.803571,0.767857,0.892857,0.785714,0.890909,0.828182,0.053228,53
60,0.010653,0.001851,0.033398,0.003152,brute,9,1,uniform,"{'algorithm': 'brute', 'n_neighbors': 9, 'p': ...",0.821429,0.821429,0.910714,0.785714,0.909091,0.849675,0.050878,37
61,0.013787,0.001555,0.018172,0.001599,brute,9,1,distance,"{'algorithm': 'brute', 'n_neighbors': 9, 'p': ...",0.839286,0.839286,0.928571,0.803571,0.909091,0.863961,0.047066,21
62,0.011686,0.001967,0.030818,0.002129,brute,9,2,uniform,"{'algorithm': 'brute', 'n_neighbors': 9, 'p': ...",0.803571,0.767857,0.857143,0.732143,0.890909,0.810325,0.057701,57
63,0.011372,0.002213,0.014308,0.002155,brute,9,2,distance,"{'algorithm': 'brute', 'n_neighbors': 9, 'p': ...",0.785714,0.767857,0.892857,0.803571,0.909091,0.831818,0.057812,49

In [12]:
grid_predictions = grid.predict(x_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

In [14]:
print(cm)

[[42  3]
 [19 56]]

In [15]:
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [16]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.69      0.93      0.79        45
           1       0.95      0.75      0.84        75

    accuracy                           0.82       120
   macro avg       0.82      0.84      0.81       120
weighted avg       0.85      0.82      0.82       120

In [17]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

np.float64(0.9037037037037037)