In [27]:
import pandas as pd   # it's a library used process the tubular data

In [28]:
dataset= pd.read_csv("CKD.csv")  # function of pandas used to load the data
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [29]:
dataset=pd.get_dummies(dataset) #to create dummies value for categorical text
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,cad_no,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes,classification_no,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,True,False,False,True,False,True,True,False,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,True,True,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,True,True,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,True,True,False,False,True,False,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,True,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,True,True,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,False,True,False,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,True,False,True,False,True,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,False,True,False,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,True,True,False,True,False,True,False

In [30]:
dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false
dataset

C:\Users\jayas\AppData\Local\Temp\ipykernel_4196\2063786219.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,cad_no,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes,classification_no,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,1,0,1,1,0,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,1,1,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,1,1,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,1,1,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,1,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,1,1,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,1,0,1,0,1,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,1,1,0,1,0,1,0

In [31]:
dataset = dataset.drop(columns=['cad_no', 'classification_no', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_a', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_abnormal',
       'rbc_normal', 'pc_abnormal', 'pc_normal', 'pcc_notpresent',
       'pcc_present', 'ba_notpresent', 'ba_present', 'htn_no', 'htn_yes'])# drop columns from the dataset
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,dm_no,dm_yes,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,1,0,0,0,1,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,1,0,0,0,1,1,0,1,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,1,0,0,0,1,1,0,1,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,1,0,0,0,1,1,0,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,1,0,0,0,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,1,0,0,0,1,1,0,1,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,0,1,0,0,1,1,0,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,0,1,0,1,0,1,0,1,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,0,1,0,0,1,1,0,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,1,0,0,0,1,1,0,1,0,0

In [32]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 
       'dm_no', 'dm_yes', 'cad_yes', 'appet_poor', 'appet_yes', 'pe_poor',
       'pe_yes', 'ane_no', 'ane_yes']]  # split input and output to get input from dataset 
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,dm_no,dm_yes,cad_yes,appet_poor,appet_yes,pe_poor,pe_yes,ane_no,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,1,0,0,0,1,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,1,0,0,0,1,1,0,1,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,1,0,0,0,1,1,0,1,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,1,0,0,0,1,1,0,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,1,0,0,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,1,0,0,0,1,1,0,1,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,0,1,0,0,1,1,0,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,0,1,0,1,0,1,0,1,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,0,1,0,0,1,1,0,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,1,0,0,0,1,1,0,1,0

In [33]:
dependent=dataset[['classification_yes']] # get output from dataset
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [34]:
from sklearn.model_selection import train_test_split  # sklearn library for machine learning
x_train,x_test,y_train,y_test = train_test_split(independent, dependent,test_size=0.30,random_state=0)

In [35]:
from sklearn.model_selection import GridSearchCV # built model for grid search
from sklearn.ensemble import RandomForestClassifier
param_grid = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': [None, 5, 10, 15],
    'n_estimators': [100, 200]
}

grid= GridSearchCV(RandomForestClassifier(),param_grid, refit=True, verbose=3, n_jobs=-1, scoring= 'f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [None, 5, 10, 15],
                         'n_estimators': [100, 200]},
             scoring='f1_weighted', verbose=3)

In [14]:
re=grid.cv_results_ # print best parameter after tuning

In [36]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.650664,0.028291,0.060531,0.005751,gini,None,100,"{'criterion': 'gini', 'max_depth': None, 'n_es...",1.0,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,8
1,1.313309,0.080320,0.104398,0.014559,gini,None,200,"{'criterion': 'gini', 'max_depth': None, 'n_es...",1.0,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,8
2,0.716471,0.017432,0.063851,0.003026,gini,5,100,"{'criterion': 'gini', 'max_depth': 5, 'n_estim...",1.0,0.945469,0.947015,0.964286,0.981728,0.967700,0.020851,24
3,1.314776,0.025665,0.094698,0.003602,gini,5,200,"{'criterion': 'gini', 'max_depth': 5, 'n_estim...",1.0,0.963889,0.982221,0.982051,1.000000,0.985632,0.013491,6
4,0.706338,0.013708,0.064697,0.004274,gini,10,100,"{'criterion': 'gini', 'max_depth': 10, 'n_esti...",1.0,0.982051,0.982221,0.964286,0.981728,0.982057,0.011295,15
5,1.356229,0.023775,0.091099,0.005325,gini,10,200,"{'criterion': 'gini', 'max_depth': 10, 'n_esti...",1.0,0.982051,0.982221,0.964286,1.000000,0.985712,0.013364,4
6,0.735307,0.063162,0.070261,0.018417,gini,15,100,"{'criterion': 'gini', 'max_depth': 15, 'n_esti...",1.0,0.946153,0.982221,0.964286,1.000000,0.978532,0.020913,19
7,1.426975,0.039574,0.094052,0.004872,gini,15,200,"{'criterion': 'gini', 'max_depth': 15, 'n_esti...",1.0,0.982051,0.982221,0.982051,1.000000,0.989265,0.008766,1
8,0.716341,0.033584,0.064076,0.007482,entropy,None,100,"{'criterion': 'entropy', 'max_depth': None, 'n...",1.0,0.964286,0.964572,0.964286,1.000000,0.978629,0.017450,17
9,1.386987,0.018270,0.098545,0.006486,entropy,None,200,"{'criterion': 'entropy', 'max_depth': None, 'n...",1.0,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,8
10,0.685583,0.015460,0.061673,0.005231,entropy,5,100,"{'criterion': 'entropy', 'max_depth': 5, 'n_es...",1.0,0.963889,0.947015,0.982051,1.000000,0.978591,0.020697,18
11,1.380363,0.025560,0.096209,0.002324,entropy,5,200,"{'criterion': 'entropy', 'max_depth': 5, 'n_es...",1.0,0.982051,0.947015,0.964286,1.000000,0.978670,0.020641,16
12,0.722892,0.021652,0.058420,0.010027,entropy,10,100,"{'criterion': 'entropy', 'max_depth': 10, 'n_e...",1.0,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,8
13,1.336622,0.034684,0.091107,0.006436,entropy,10,200,"{'criterion': 'entropy', 'max_depth': 10, 'n_e...",1.0,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,22
14,0.675584,0.012269,0.062013,0.003252,entropy,15,100,"{'criterion': 'entropy', 'max_depth': 15, 'n_e...",1.0,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,22
15,1.367155,0.012498,0.095395,0.004543,entropy,15,200,"{'criterion': 'entropy', 'max_depth': 15, 'n_e...",1.0,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,8
16,0.698293,0.022097,0.065756,0.006467,log_loss,None,100,"{'criterion': 'log_loss', 'max_depth': None, '...",1.0,0.982051,0.964572,0.982051,1.000000,0.985735,0.013281,2
17,1.401777,0.042860,0.091775,0.004182,log_loss,None,200,"{'criterion': 'log_loss', 'max_depth': None, '...",1.0,0.982051,0.964572,0.982051,1.000000,0.985735,0.013281,2
18,0.692919,0.032053,0.062237,0.004146,log_loss,5,100,"{'criterion': 'log_loss', 'max_depth': 5, 'n_e...",1.0,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,21
19,1.352868,0.019662,0.094109,0.002931,log_loss,5,200,"{'criterion': 'log_loss', 'max_depth': 5, 'n_e...",1.0,0.963889,0.982221,0.982051,1.000000,0.985632,0.013491,6
20,0.671802,0.032760,0.064959,0.006695,log_loss,10,100,"{'criterion': 'log_loss', 'max_depth': 10, 'n_...",1.0,0.982051,0.982221,0.964286,1.000000,0.985712,0.013364,4
21,1.355696,0.013174,0.088762,0.007144,log_loss,10,200,"{'criterion': 'log_loss', 'max_depth': 10, 'n_...",1.0,0.963889,0.982221,0.964286,1.000000,0.982079,0.016061,14
22,0.690463,0.016262,0.059542,0.004673,log_loss,15,100,"{'criterion': 'log_loss', 'max_depth': 15, 'n_...",1.0,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,8
23,1.193578,0.037848,0.083130,0.011013,log_loss,15,200,"{'criterion': 'log_loss', 'max_depth': 15, 'n_...",1.0,0.945469,0.982221,0.964286,1.000000,0.978395,0.021125,20

In [37]:
grid_predictions = grid.predict(x_test)

In [38]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

In [39]:
print(cm)

[[43  2]
 [ 2 73]]

In [40]:
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [41]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        45
           1       0.97      0.97      0.97        75

    accuracy                           0.97       120
   macro avg       0.96      0.96      0.96       120
weighted avg       0.97      0.97      0.97       120

In [46]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

np.float64(0.9967407407407407)

In [43]:
import pickle   # store the model
filename = "finalized_model_random_forest_classifier.sav" 
pickle.dump(grid,open(filename,"wb"))

In [44]:
load_model=pickle.load(open("finalized_model_random_forest_classifier.sav" ,"rb")) # load the model from the file
result=load_model.predict([[2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,1,0,0,0,1,0,1,1,0]])

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [45]:
result

array([1])